version: '2'
services:
  web-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  load-generator:
    image: tutum/curl
    stdin_open: true
    tty: true
    links:
    - web-lb:web-endpoint
    command:
    - bash
    - -c
    - while true ; do curl web-endpoint/name.html ; sleep 1 ; done
    labels:
      io.rancher.scheduler.global: 'true'
  web:
    image: sangeetha/testnewhostrouting
    stdin_open: true
    tty: true
    command:
    - bash
    - -c
    - nginx & sleep "$${RANDOM:0:4}"
